//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WpfApplication1.se.stockholm.test.bokabostad {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1086.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DefaultServiceSoap", Namespace="http://bokabostad.stockholm.se/Bostoc2005/")]
    public partial class DefaultService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GatuadressListOperationCompleted;
        
        private System.Threading.SendOrPostCallback TillgangligaKokstyperListOperationCompleted;
        
        private System.Threading.SendOrPostCallback TillgangligaBadrumstyperListOperationCompleted;
        
        private System.Threading.SendOrPostCallback TillgangligaHisstyperListOperationCompleted;
        
        private System.Threading.SendOrPostCallback TillgangligaBalkongtyperListOperationCompleted;
        
        private System.Threading.SendOrPostCallback TillgangligaBeskrivningstyperListOperationCompleted;
        
        private System.Threading.SendOrPostCallback RelateradeBolagOperationCompleted;
        
        private System.Threading.SendOrPostCallback StandardkravListOperationCompleted;
        
        private System.Threading.SendOrPostCallback LagenhetInsertOperationCompleted;
        
        private System.Threading.SendOrPostCallback HyresgastforslagSvarUpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback HyresgastforslagGetDokumentOperationCompleted;
        
        private System.Threading.SendOrPostCallback DirektInloggningOperationCompleted;
        
        private System.Threading.SendOrPostCallback HyresgastforslagFranBFOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DefaultService() {
            this.Url = global::WpfApplication1.Properties.Settings.Default.WpfApplication1_se_stockholm_test_bokabostad_DefaultService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GatuadressListCompletedEventHandler GatuadressListCompleted;
        
        /// <remarks/>
        public event TillgangligaKokstyperListCompletedEventHandler TillgangligaKokstyperListCompleted;
        
        /// <remarks/>
        public event TillgangligaBadrumstyperListCompletedEventHandler TillgangligaBadrumstyperListCompleted;
        
        /// <remarks/>
        public event TillgangligaHisstyperListCompletedEventHandler TillgangligaHisstyperListCompleted;
        
        /// <remarks/>
        public event TillgangligaBalkongtyperListCompletedEventHandler TillgangligaBalkongtyperListCompleted;
        
        /// <remarks/>
        public event TillgangligaBeskrivningstyperListCompletedEventHandler TillgangligaBeskrivningstyperListCompleted;
        
        /// <remarks/>
        public event RelateradeBolagCompletedEventHandler RelateradeBolagCompleted;
        
        /// <remarks/>
        public event StandardkravListCompletedEventHandler StandardkravListCompleted;
        
        /// <remarks/>
        public event LagenhetInsertCompletedEventHandler LagenhetInsertCompleted;
        
        /// <remarks/>
        public event HyresgastforslagSvarUpdateCompletedEventHandler HyresgastforslagSvarUpdateCompleted;
        
        /// <remarks/>
        public event HyresgastforslagGetDokumentCompletedEventHandler HyresgastforslagGetDokumentCompleted;
        
        /// <remarks/>
        public event DirektInloggningCompletedEventHandler DirektInloggningCompleted;
        
        /// <remarks/>
        public event HyresgastforslagFranBFCompletedEventHandler HyresgastforslagFranBFCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bokabostad.stockholm.se/Bostoc2005/GatuadressList", RequestNamespace="http://bokabostad.stockholm.se/Bostoc2005/", ResponseNamespace="http://bokabostad.stockholm.se/Bostoc2005/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GatuadressList(string gatunamn, string gatunummer, int postnummer) {
            object[] results = this.Invoke("GatuadressList", new object[] {
                        gatunamn,
                        gatunummer,
                        postnummer});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GatuadressListAsync(string gatunamn, string gatunummer, int postnummer) {
            this.GatuadressListAsync(gatunamn, gatunummer, postnummer, null);
        }
        
        /// <remarks/>
        public void GatuadressListAsync(string gatunamn, string gatunummer, int postnummer, object userState) {
            if ((this.GatuadressListOperationCompleted == null)) {
                this.GatuadressListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGatuadressListOperationCompleted);
            }
            this.InvokeAsync("GatuadressList", new object[] {
                        gatunamn,
                        gatunummer,
                        postnummer}, this.GatuadressListOperationCompleted, userState);
        }
        
        private void OnGatuadressListOperationCompleted(object arg) {
            if ((this.GatuadressListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GatuadressListCompleted(this, new GatuadressListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bokabostad.stockholm.se/Bostoc2005/TillgangligaKokstyperList", RequestNamespace="http://bokabostad.stockholm.se/Bostoc2005/", ResponseNamespace="http://bokabostad.stockholm.se/Bostoc2005/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet TillgangligaKokstyperList() {
            object[] results = this.Invoke("TillgangligaKokstyperList", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void TillgangligaKokstyperListAsync() {
            this.TillgangligaKokstyperListAsync(null);
        }
        
        /// <remarks/>
        public void TillgangligaKokstyperListAsync(object userState) {
            if ((this.TillgangligaKokstyperListOperationCompleted == null)) {
                this.TillgangligaKokstyperListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTillgangligaKokstyperListOperationCompleted);
            }
            this.InvokeAsync("TillgangligaKokstyperList", new object[0], this.TillgangligaKokstyperListOperationCompleted, userState);
        }
        
        private void OnTillgangligaKokstyperListOperationCompleted(object arg) {
            if ((this.TillgangligaKokstyperListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TillgangligaKokstyperListCompleted(this, new TillgangligaKokstyperListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bokabostad.stockholm.se/Bostoc2005/TillgangligaBadrumstyperList", RequestNamespace="http://bokabostad.stockholm.se/Bostoc2005/", ResponseNamespace="http://bokabostad.stockholm.se/Bostoc2005/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet TillgangligaBadrumstyperList() {
            object[] results = this.Invoke("TillgangligaBadrumstyperList", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void TillgangligaBadrumstyperListAsync() {
            this.TillgangligaBadrumstyperListAsync(null);
        }
        
        /// <remarks/>
        public void TillgangligaBadrumstyperListAsync(object userState) {
            if ((this.TillgangligaBadrumstyperListOperationCompleted == null)) {
                this.TillgangligaBadrumstyperListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTillgangligaBadrumstyperListOperationCompleted);
            }
            this.InvokeAsync("TillgangligaBadrumstyperList", new object[0], this.TillgangligaBadrumstyperListOperationCompleted, userState);
        }
        
        private void OnTillgangligaBadrumstyperListOperationCompleted(object arg) {
            if ((this.TillgangligaBadrumstyperListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TillgangligaBadrumstyperListCompleted(this, new TillgangligaBadrumstyperListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bokabostad.stockholm.se/Bostoc2005/TillgangligaHisstyperList", RequestNamespace="http://bokabostad.stockholm.se/Bostoc2005/", ResponseNamespace="http://bokabostad.stockholm.se/Bostoc2005/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet TillgangligaHisstyperList() {
            object[] results = this.Invoke("TillgangligaHisstyperList", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void TillgangligaHisstyperListAsync() {
            this.TillgangligaHisstyperListAsync(null);
        }
        
        /// <remarks/>
        public void TillgangligaHisstyperListAsync(object userState) {
            if ((this.TillgangligaHisstyperListOperationCompleted == null)) {
                this.TillgangligaHisstyperListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTillgangligaHisstyperListOperationCompleted);
            }
            this.InvokeAsync("TillgangligaHisstyperList", new object[0], this.TillgangligaHisstyperListOperationCompleted, userState);
        }
        
        private void OnTillgangligaHisstyperListOperationCompleted(object arg) {
            if ((this.TillgangligaHisstyperListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TillgangligaHisstyperListCompleted(this, new TillgangligaHisstyperListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bokabostad.stockholm.se/Bostoc2005/TillgangligaBalkongtyperList", RequestNamespace="http://bokabostad.stockholm.se/Bostoc2005/", ResponseNamespace="http://bokabostad.stockholm.se/Bostoc2005/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet TillgangligaBalkongtyperList() {
            object[] results = this.Invoke("TillgangligaBalkongtyperList", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void TillgangligaBalkongtyperListAsync() {
            this.TillgangligaBalkongtyperListAsync(null);
        }
        
        /// <remarks/>
        public void TillgangligaBalkongtyperListAsync(object userState) {
            if ((this.TillgangligaBalkongtyperListOperationCompleted == null)) {
                this.TillgangligaBalkongtyperListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTillgangligaBalkongtyperListOperationCompleted);
            }
            this.InvokeAsync("TillgangligaBalkongtyperList", new object[0], this.TillgangligaBalkongtyperListOperationCompleted, userState);
        }
        
        private void OnTillgangligaBalkongtyperListOperationCompleted(object arg) {
            if ((this.TillgangligaBalkongtyperListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TillgangligaBalkongtyperListCompleted(this, new TillgangligaBalkongtyperListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bokabostad.stockholm.se/Bostoc2005/TillgangligaBeskrivningstyperList", RequestNamespace="http://bokabostad.stockholm.se/Bostoc2005/", ResponseNamespace="http://bokabostad.stockholm.se/Bostoc2005/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet TillgangligaBeskrivningstyperList() {
            object[] results = this.Invoke("TillgangligaBeskrivningstyperList", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void TillgangligaBeskrivningstyperListAsync() {
            this.TillgangligaBeskrivningstyperListAsync(null);
        }
        
        /// <remarks/>
        public void TillgangligaBeskrivningstyperListAsync(object userState) {
            if ((this.TillgangligaBeskrivningstyperListOperationCompleted == null)) {
                this.TillgangligaBeskrivningstyperListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTillgangligaBeskrivningstyperListOperationCompleted);
            }
            this.InvokeAsync("TillgangligaBeskrivningstyperList", new object[0], this.TillgangligaBeskrivningstyperListOperationCompleted, userState);
        }
        
        private void OnTillgangligaBeskrivningstyperListOperationCompleted(object arg) {
            if ((this.TillgangligaBeskrivningstyperListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TillgangligaBeskrivningstyperListCompleted(this, new TillgangligaBeskrivningstyperListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bokabostad.stockholm.se/Bostoc2005/RelateradeBolag", RequestNamespace="http://bokabostad.stockholm.se/Bostoc2005/", ResponseNamespace="http://bokabostad.stockholm.se/Bostoc2005/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RelateradeBolag(string organisationsnummer, string losenord, string fastighetsagareOrgnr, string forvaltningsbolagOrgnr) {
            object[] results = this.Invoke("RelateradeBolag", new object[] {
                        organisationsnummer,
                        losenord,
                        fastighetsagareOrgnr,
                        forvaltningsbolagOrgnr});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RelateradeBolagAsync(string organisationsnummer, string losenord, string fastighetsagareOrgnr, string forvaltningsbolagOrgnr) {
            this.RelateradeBolagAsync(organisationsnummer, losenord, fastighetsagareOrgnr, forvaltningsbolagOrgnr, null);
        }
        
        /// <remarks/>
        public void RelateradeBolagAsync(string organisationsnummer, string losenord, string fastighetsagareOrgnr, string forvaltningsbolagOrgnr, object userState) {
            if ((this.RelateradeBolagOperationCompleted == null)) {
                this.RelateradeBolagOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRelateradeBolagOperationCompleted);
            }
            this.InvokeAsync("RelateradeBolag", new object[] {
                        organisationsnummer,
                        losenord,
                        fastighetsagareOrgnr,
                        forvaltningsbolagOrgnr}, this.RelateradeBolagOperationCompleted, userState);
        }
        
        private void OnRelateradeBolagOperationCompleted(object arg) {
            if ((this.RelateradeBolagCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RelateradeBolagCompleted(this, new RelateradeBolagCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bokabostad.stockholm.se/Bostoc2005/StandardkravList", RequestNamespace="http://bokabostad.stockholm.se/Bostoc2005/", ResponseNamespace="http://bokabostad.stockholm.se/Bostoc2005/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet StandardkravList(string organisationsnummer, string losenord, string fastighetsagareOrgnr) {
            object[] results = this.Invoke("StandardkravList", new object[] {
                        organisationsnummer,
                        losenord,
                        fastighetsagareOrgnr});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void StandardkravListAsync(string organisationsnummer, string losenord, string fastighetsagareOrgnr) {
            this.StandardkravListAsync(organisationsnummer, losenord, fastighetsagareOrgnr, null);
        }
        
        /// <remarks/>
        public void StandardkravListAsync(string organisationsnummer, string losenord, string fastighetsagareOrgnr, object userState) {
            if ((this.StandardkravListOperationCompleted == null)) {
                this.StandardkravListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStandardkravListOperationCompleted);
            }
            this.InvokeAsync("StandardkravList", new object[] {
                        organisationsnummer,
                        losenord,
                        fastighetsagareOrgnr}, this.StandardkravListOperationCompleted, userState);
        }
        
        private void OnStandardkravListOperationCompleted(object arg) {
            if ((this.StandardkravListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StandardkravListCompleted(this, new StandardkravListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bokabostad.stockholm.se/Bostoc2005/LagenhetInsert", RequestNamespace="http://bokabostad.stockholm.se/Bostoc2005/", ResponseNamespace="http://bokabostad.stockholm.se/Bostoc2005/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool LagenhetInsert(
                    string organisationsnummer, 
                    string losenord, 
                    string lagenhetsnummer, 
                    int gatuadressId, 
                    FastighetsTyp fastighetstyp, 
                    LägenhetTyp lagenhetstyp, 
                    string fastighetsagareOrgnr, 
                    string forvaltningsbolagOrgnr, 
                    string kontaktperson, 
                    string antalRum, 
                    int yta, 
                    int hyra, 
                    string vaning, 
                    int kokstypId, 
                    int badrumstypId, 
                    int hisstypId, 
                    int balkongtypId, 
                    int[] beskrivningstypId, 
                    string beskrivning, 
                    BildObjekt[] lghbild, 
                    UrlObjekt[] lghurl, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<System.DateTime> inflyttningsdatum, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<System.DateTime> senasteforslagsdatum, 
                    int[] kravId, 
                    string internVisningsinformation, 
                    string internNotering, 
                    Kö avseddForKo) {
            object[] results = this.Invoke("LagenhetInsert", new object[] {
                        organisationsnummer,
                        losenord,
                        lagenhetsnummer,
                        gatuadressId,
                        fastighetstyp,
                        lagenhetstyp,
                        fastighetsagareOrgnr,
                        forvaltningsbolagOrgnr,
                        kontaktperson,
                        antalRum,
                        yta,
                        hyra,
                        vaning,
                        kokstypId,
                        badrumstypId,
                        hisstypId,
                        balkongtypId,
                        beskrivningstypId,
                        beskrivning,
                        lghbild,
                        lghurl,
                        inflyttningsdatum,
                        senasteforslagsdatum,
                        kravId,
                        internVisningsinformation,
                        internNotering,
                        avseddForKo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void LagenhetInsertAsync(
                    string organisationsnummer, 
                    string losenord, 
                    string lagenhetsnummer, 
                    int gatuadressId, 
                    FastighetsTyp fastighetstyp, 
                    LägenhetTyp lagenhetstyp, 
                    string fastighetsagareOrgnr, 
                    string forvaltningsbolagOrgnr, 
                    string kontaktperson, 
                    string antalRum, 
                    int yta, 
                    int hyra, 
                    string vaning, 
                    int kokstypId, 
                    int badrumstypId, 
                    int hisstypId, 
                    int balkongtypId, 
                    int[] beskrivningstypId, 
                    string beskrivning, 
                    BildObjekt[] lghbild, 
                    UrlObjekt[] lghurl, 
                    System.Nullable<System.DateTime> inflyttningsdatum, 
                    System.Nullable<System.DateTime> senasteforslagsdatum, 
                    int[] kravId, 
                    string internVisningsinformation, 
                    string internNotering, 
                    Kö avseddForKo) {
            this.LagenhetInsertAsync(organisationsnummer, losenord, lagenhetsnummer, gatuadressId, fastighetstyp, lagenhetstyp, fastighetsagareOrgnr, forvaltningsbolagOrgnr, kontaktperson, antalRum, yta, hyra, vaning, kokstypId, badrumstypId, hisstypId, balkongtypId, beskrivningstypId, beskrivning, lghbild, lghurl, inflyttningsdatum, senasteforslagsdatum, kravId, internVisningsinformation, internNotering, avseddForKo, null);
        }
        
        /// <remarks/>
        public void LagenhetInsertAsync(
                    string organisationsnummer, 
                    string losenord, 
                    string lagenhetsnummer, 
                    int gatuadressId, 
                    FastighetsTyp fastighetstyp, 
                    LägenhetTyp lagenhetstyp, 
                    string fastighetsagareOrgnr, 
                    string forvaltningsbolagOrgnr, 
                    string kontaktperson, 
                    string antalRum, 
                    int yta, 
                    int hyra, 
                    string vaning, 
                    int kokstypId, 
                    int badrumstypId, 
                    int hisstypId, 
                    int balkongtypId, 
                    int[] beskrivningstypId, 
                    string beskrivning, 
                    BildObjekt[] lghbild, 
                    UrlObjekt[] lghurl, 
                    System.Nullable<System.DateTime> inflyttningsdatum, 
                    System.Nullable<System.DateTime> senasteforslagsdatum, 
                    int[] kravId, 
                    string internVisningsinformation, 
                    string internNotering, 
                    Kö avseddForKo, 
                    object userState) {
            if ((this.LagenhetInsertOperationCompleted == null)) {
                this.LagenhetInsertOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLagenhetInsertOperationCompleted);
            }
            this.InvokeAsync("LagenhetInsert", new object[] {
                        organisationsnummer,
                        losenord,
                        lagenhetsnummer,
                        gatuadressId,
                        fastighetstyp,
                        lagenhetstyp,
                        fastighetsagareOrgnr,
                        forvaltningsbolagOrgnr,
                        kontaktperson,
                        antalRum,
                        yta,
                        hyra,
                        vaning,
                        kokstypId,
                        badrumstypId,
                        hisstypId,
                        balkongtypId,
                        beskrivningstypId,
                        beskrivning,
                        lghbild,
                        lghurl,
                        inflyttningsdatum,
                        senasteforslagsdatum,
                        kravId,
                        internVisningsinformation,
                        internNotering,
                        avseddForKo}, this.LagenhetInsertOperationCompleted, userState);
        }
        
        private void OnLagenhetInsertOperationCompleted(object arg) {
            if ((this.LagenhetInsertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LagenhetInsertCompleted(this, new LagenhetInsertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bokabostad.stockholm.se/Bostoc2005/HyresgastforslagSvarUpdate", RequestNamespace="http://bokabostad.stockholm.se/Bostoc2005/", ResponseNamespace="http://bokabostad.stockholm.se/Bostoc2005/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool HyresgastforslagSvarUpdate(string organisationsnummer, string losenord, int hyresgastforslagId, Svar godkannande, string motivering) {
            object[] results = this.Invoke("HyresgastforslagSvarUpdate", new object[] {
                        organisationsnummer,
                        losenord,
                        hyresgastforslagId,
                        godkannande,
                        motivering});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void HyresgastforslagSvarUpdateAsync(string organisationsnummer, string losenord, int hyresgastforslagId, Svar godkannande, string motivering) {
            this.HyresgastforslagSvarUpdateAsync(organisationsnummer, losenord, hyresgastforslagId, godkannande, motivering, null);
        }
        
        /// <remarks/>
        public void HyresgastforslagSvarUpdateAsync(string organisationsnummer, string losenord, int hyresgastforslagId, Svar godkannande, string motivering, object userState) {
            if ((this.HyresgastforslagSvarUpdateOperationCompleted == null)) {
                this.HyresgastforslagSvarUpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHyresgastforslagSvarUpdateOperationCompleted);
            }
            this.InvokeAsync("HyresgastforslagSvarUpdate", new object[] {
                        organisationsnummer,
                        losenord,
                        hyresgastforslagId,
                        godkannande,
                        motivering}, this.HyresgastforslagSvarUpdateOperationCompleted, userState);
        }
        
        private void OnHyresgastforslagSvarUpdateOperationCompleted(object arg) {
            if ((this.HyresgastforslagSvarUpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HyresgastforslagSvarUpdateCompleted(this, new HyresgastforslagSvarUpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bokabostad.stockholm.se/Bostoc2005/HyresgastforslagGetDokument", RequestNamespace="http://bokabostad.stockholm.se/Bostoc2005/", ResponseNamespace="http://bokabostad.stockholm.se/Bostoc2005/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] HyresgastforslagGetDokument(string organisationsnummer, string losenord, int hyresgastforslagId, string dokumentId) {
            object[] results = this.Invoke("HyresgastforslagGetDokument", new object[] {
                        organisationsnummer,
                        losenord,
                        hyresgastforslagId,
                        dokumentId});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void HyresgastforslagGetDokumentAsync(string organisationsnummer, string losenord, int hyresgastforslagId, string dokumentId) {
            this.HyresgastforslagGetDokumentAsync(organisationsnummer, losenord, hyresgastforslagId, dokumentId, null);
        }
        
        /// <remarks/>
        public void HyresgastforslagGetDokumentAsync(string organisationsnummer, string losenord, int hyresgastforslagId, string dokumentId, object userState) {
            if ((this.HyresgastforslagGetDokumentOperationCompleted == null)) {
                this.HyresgastforslagGetDokumentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHyresgastforslagGetDokumentOperationCompleted);
            }
            this.InvokeAsync("HyresgastforslagGetDokument", new object[] {
                        organisationsnummer,
                        losenord,
                        hyresgastforslagId,
                        dokumentId}, this.HyresgastforslagGetDokumentOperationCompleted, userState);
        }
        
        private void OnHyresgastforslagGetDokumentOperationCompleted(object arg) {
            if ((this.HyresgastforslagGetDokumentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HyresgastforslagGetDokumentCompleted(this, new HyresgastforslagGetDokumentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bokabostad.stockholm.se/Bostoc2005/DirektInloggning", RequestNamespace="http://bokabostad.stockholm.se/Bostoc2005/", ResponseNamespace="http://bokabostad.stockholm.se/Bostoc2005/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DirektInloggning(string organisationsnummer, string losenord, string lagenhetsnummer) {
            object[] results = this.Invoke("DirektInloggning", new object[] {
                        organisationsnummer,
                        losenord,
                        lagenhetsnummer});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DirektInloggningAsync(string organisationsnummer, string losenord, string lagenhetsnummer) {
            this.DirektInloggningAsync(organisationsnummer, losenord, lagenhetsnummer, null);
        }
        
        /// <remarks/>
        public void DirektInloggningAsync(string organisationsnummer, string losenord, string lagenhetsnummer, object userState) {
            if ((this.DirektInloggningOperationCompleted == null)) {
                this.DirektInloggningOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDirektInloggningOperationCompleted);
            }
            this.InvokeAsync("DirektInloggning", new object[] {
                        organisationsnummer,
                        losenord,
                        lagenhetsnummer}, this.DirektInloggningOperationCompleted, userState);
        }
        
        private void OnDirektInloggningOperationCompleted(object arg) {
            if ((this.DirektInloggningCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DirektInloggningCompleted(this, new DirektInloggningCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bokabostad.stockholm.se/Bostoc2005/HyresgastforslagFranBF", RequestNamespace="http://bokabostad.stockholm.se/Bostoc2005/", ResponseNamespace="http://bokabostad.stockholm.se/Bostoc2005/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool HyresgastforslagFranBF(string pwd, string xml) {
            object[] results = this.Invoke("HyresgastforslagFranBF", new object[] {
                        pwd,
                        xml});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void HyresgastforslagFranBFAsync(string pwd, string xml) {
            this.HyresgastforslagFranBFAsync(pwd, xml, null);
        }
        
        /// <remarks/>
        public void HyresgastforslagFranBFAsync(string pwd, string xml, object userState) {
            if ((this.HyresgastforslagFranBFOperationCompleted == null)) {
                this.HyresgastforslagFranBFOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHyresgastforslagFranBFOperationCompleted);
            }
            this.InvokeAsync("HyresgastforslagFranBF", new object[] {
                        pwd,
                        xml}, this.HyresgastforslagFranBFOperationCompleted, userState);
        }
        
        private void OnHyresgastforslagFranBFOperationCompleted(object arg) {
            if ((this.HyresgastforslagFranBFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HyresgastforslagFranBFCompleted(this, new HyresgastforslagFranBFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1086.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bokabostad.stockholm.se/Bostoc2005/")]
    public enum FastighetsTyp {
        
        /// <remarks/>
        Ingen,
        
        /// <remarks/>
        Succession,
        
        /// <remarks/>
        Nyproduktion,
        
        /// <remarks/>
        Ombyggnation,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1086.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bokabostad.stockholm.se/Bostoc2005/")]
    public enum LägenhetTyp {
        
        /// <remarks/>
        Ingen,
        
        /// <remarks/>
        Hyresrätt,
        
        /// <remarks/>
        Korttidskontrakt,
        
        /// <remarks/>
        Ungdomslägenhet,
        
        /// <remarks/>
        Studentlägenhet,
        
        /// <remarks/>
        SeniorbostadMin55,
        
        /// <remarks/>
        SeniorbostadMin65,
        
        /// <remarks/>
        Handikappanpassad,
        
        /// <remarks/>
        Allergianpassad,
        
        /// <remarks/>
        Ateljelägenhet,
        
        /// <remarks/>
        Kollektivhuslägenhet,
        
        /// <remarks/>
        Pensionärslägenhet,
        
        /// <remarks/>
        Hyresradhus,
        
        /// <remarks/>
        Studentkorridor,
        
        /// <remarks/>
        Trygghetsboende,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1086.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bokabostad.stockholm.se/Bostoc2005/")]
    public partial class BildObjekt {
        
        private string beskrivningField;
        
        private string filnamnField;
        
        private byte[] filField;
        
        /// <remarks/>
        public string Beskrivning {
            get {
                return this.beskrivningField;
            }
            set {
                this.beskrivningField = value;
            }
        }
        
        /// <remarks/>
        public string Filnamn {
            get {
                return this.filnamnField;
            }
            set {
                this.filnamnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Fil {
            get {
                return this.filField;
            }
            set {
                this.filField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1086.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bokabostad.stockholm.se/Bostoc2005/")]
    public partial class UrlObjekt {
        
        private string beskrivningField;
        
        private string urlField;
        
        /// <remarks/>
        public string Beskrivning {
            get {
                return this.beskrivningField;
            }
            set {
                this.beskrivningField = value;
            }
        }
        
        /// <remarks/>
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1086.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bokabostad.stockholm.se/Bostoc2005/")]
    public enum Kö {
        
        /// <remarks/>
        Alla,
        
        /// <remarks/>
        Bostadskön,
        
        /// <remarks/>
        Huddingekön,
        
        /// <remarks/>
        HusbyMandamuskön,
        
        /// <remarks/>
        Vallentunakön,
        
        /// <remarks/>
        Hebakön,
        
        /// <remarks/>
        Arbetarebostadsfondskön,
        
        /// <remarks/>
        FondenUngdom,
        
        /// <remarks/>
        Botkyrkakön,
        
        /// <remarks/>
        Internkön,
        
        /// <remarks/>
        SveboStudent,
        
        /// <remarks/>
        VasakronanStudent,
        
        /// <remarks/>
        TrygghetsboendeStockholm,
        
        /// <remarks/>
        Värmdökön,
        
        /// <remarks/>
        Bovivakön,
        
        /// <remarks/>
        JohnMattsonkön,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1086.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bokabostad.stockholm.se/Bostoc2005/")]
    public enum Svar {
        
        /// <remarks/>
        Inget,
        
        /// <remarks/>
        Ja,
        
        /// <remarks/>
        Nej,
        
        /// <remarks/>
        Avhopp,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1086.0")]
    public delegate void GatuadressListCompletedEventHandler(object sender, GatuadressListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1086.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GatuadressListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GatuadressListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1086.0")]
    public delegate void TillgangligaKokstyperListCompletedEventHandler(object sender, TillgangligaKokstyperListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1086.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TillgangligaKokstyperListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TillgangligaKokstyperListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1086.0")]
    public delegate void TillgangligaBadrumstyperListCompletedEventHandler(object sender, TillgangligaBadrumstyperListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1086.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TillgangligaBadrumstyperListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TillgangligaBadrumstyperListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1086.0")]
    public delegate void TillgangligaHisstyperListCompletedEventHandler(object sender, TillgangligaHisstyperListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1086.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TillgangligaHisstyperListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TillgangligaHisstyperListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1086.0")]
    public delegate void TillgangligaBalkongtyperListCompletedEventHandler(object sender, TillgangligaBalkongtyperListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1086.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TillgangligaBalkongtyperListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TillgangligaBalkongtyperListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1086.0")]
    public delegate void TillgangligaBeskrivningstyperListCompletedEventHandler(object sender, TillgangligaBeskrivningstyperListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1086.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TillgangligaBeskrivningstyperListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TillgangligaBeskrivningstyperListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1086.0")]
    public delegate void RelateradeBolagCompletedEventHandler(object sender, RelateradeBolagCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1086.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RelateradeBolagCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RelateradeBolagCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1086.0")]
    public delegate void StandardkravListCompletedEventHandler(object sender, StandardkravListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1086.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StandardkravListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StandardkravListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1086.0")]
    public delegate void LagenhetInsertCompletedEventHandler(object sender, LagenhetInsertCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1086.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LagenhetInsertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LagenhetInsertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1086.0")]
    public delegate void HyresgastforslagSvarUpdateCompletedEventHandler(object sender, HyresgastforslagSvarUpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1086.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HyresgastforslagSvarUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HyresgastforslagSvarUpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1086.0")]
    public delegate void HyresgastforslagGetDokumentCompletedEventHandler(object sender, HyresgastforslagGetDokumentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1086.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HyresgastforslagGetDokumentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HyresgastforslagGetDokumentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1086.0")]
    public delegate void DirektInloggningCompletedEventHandler(object sender, DirektInloggningCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1086.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DirektInloggningCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DirektInloggningCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1086.0")]
    public delegate void HyresgastforslagFranBFCompletedEventHandler(object sender, HyresgastforslagFranBFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1086.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HyresgastforslagFranBFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HyresgastforslagFranBFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591